# External plugins
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2

exclude:
  - "/vendor/"

# Site settings
title: Benjamin Jaros
subtitle: "Research Fellow, Hoover Institution"
name: Benjamin Jaros
email: benjaros@stanford.edu
description: > 
  Research Fellow at the Hoover Institution. Public finance, tax policy, and economic history.
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bjaros20.github.io" # the base hostname & protocol for your site
cover: "/assets/photos/flatirons_snow_jan_2017.jpg"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Pagination Settings (minimal - keeping for compatibility)
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  enabled: false
  per_page: 5
  permalink: "/page/:num/"
  sort_reverse: true

# Disqus comments - disabled
# disqus_shortname: 

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
social:
  - name: GitHub
    icon: github
    username: bjaros20
    url: https://github.com/bjaros20
    desc: View my code and projects
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Benjamin Jaros
    url: https://www.linkedin.com/in/benjamin-jaros-a3a318121/
    desc: Connect with me on LinkedIn
    share: true

  - name: Substack
    icon: rss
    username: benjaminjaros
    url: https://substack.com/@benjaminjaros
    desc: Read my policy analysis
    share: false

  - name: Twitter
    icon: twitter
    username: ""
    url: ""
    desc: Follow me on Twitter
    share: true

  - name: Facebook
    icon: facebook
    username: ""
    url: ""
    desc: Share on Facebook
    share: true

  - name: Google+
    icon: google-plus
    username: ""
    url: ""
    desc: Add me to your Circles
    share: false

  - name: YouTube
    icon: youtube
    username: ""
    url: ""
    desc: Subscribe on YouTube
    share: false

  - name: Instagram
    icon: instagram
    username: ""
    url: ""
    desc: Follow me on Instagram
    share: false

  - name: Pinterest
    icon: pinterest
    username: ""
    url: ""
    desc: Follow me on Pinterest
    share: false

  - name: SoundCloud
    icon: soundcloud
    username: ""
    url: ""
    desc: Follow me on SoundCloud
    share: false

  - name: Tumblr
    icon: tumblr
    username: ""
    url: ""
    desc: Follow me on Tumblr
    share: false

  - name: Steam
    icon: steam
    username: ""
    url: ""
    desc: Friend me on Steam
    share: false

  - name: Dribbble
    icon: dribbble
    username: ""
    url: ""
    desc: Follow me on Dribble
    share: false

  - name: Vimeo
    icon: vimeo-square
    username: ""
    url: ""
    desc: Follow me on Vimeo
    share: false

  - name: Vine
    icon: vine
    username: ""
    url: ""
    desc: Follow me on Vine
    share: false

  - name: Reddit
    icon: reddit
    username: ""
    url: ""
    desc: Share to Reddit
    share: true

  - name: "Hacker News"
    icon: hacker-news
    username: ""
    url: ""
    desc: Share to Hacker News
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bjaros20/bjaros20.github.io"
    os_rcs_type: "git"
    os_src: "git@github.com:bjaros20/bjaros20.github.io.git"

# Google analytics
# ga_tracking_id: "UA-XXXX-1"
